version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: SBP/Dockerfile
    container_name: fsp-backend
    volumes:
      - ./SBP:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: fsp-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/ssl_certs:/etc/nginx/ssl:ro
  db:
    ports:
      - "5432:5432" 
    image: postgres:14
    container_name: fsp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d  # Монтируем папку с дампом
    environment:
      POSTGRES_DB: sbp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

volumes:
  postgres_data:
