# Generated by Django 5.2 on 2025-04-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='team',
        ),
        migrations.RemoveField(
            model_name='vacancyresponse',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='win.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'В рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=25),
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
