# Generated by Django 5.2 on 2025-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0002_remove_vacancy_role_remove_vacancy_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
