# Generated by Django 5.2 on 2025-04-22 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0003_userinfo_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionorganizer',
            name='status',
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='result',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompetitionHistory',
        ),
    ]
