# Generated by Django 5.2 on 2025-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0004_remove_competitionorganizer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tg_username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
