# Generated by Django 5.2 on 2025-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0005_userinfo_tg_username_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tg_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
