# Generated by Django 5.2 on 2025-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0006_alter_userinfo_tg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
