# Generated by Django 5.2 on 2025-04-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0009_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamapplication',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to='win.competition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to='win.team'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='win.competition'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='win.userinfo'),
        ),
    ]
